 const BASE_URL = 'http://localhost:4000/';
 const MAX_SELECTED_MOVIES = 20;
 const SOCIAL_BUTTON_SIZE = 32;
 const CONFRIM_TIMEOUT = 3000;

 export {BASE_URL, MAX_SELECTED_MOVIES, SOCIAL_BUTTON_SIZE, CONFRIM_TIMEOUT};